In [15]:
% % time

UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


In [16]:
% % time
# 323 //
# 123402 LUCKY
# 7755 READY

a = '123402'
left = a[:len(a) // 2]
right = a[len(a) // 2:]
sumLeft = sum(int(x) for x in left)
sumRight = sum(int(x) for x in right)
if sumLeft == sumRight:
    print('LUCKY')
else:
    print('READY')


LUCKY
CPU times: total: 0 ns
Wall time: 0 ns


In [23]:
% % time
n = '123402'
length = len(n)
summary = 0

for i in range(length // 2):
    summary += int(n[i])

for i in range(length // 2, length):
    summary -= int(n[i])

if summary == 0:
    print("LUCKY")
else:
    print("READY")

LUCKY
CPU times: total: 0 ns
Wall time: 0 ns


In [57]:
a = 'K1KA5CB7'
b = sorted(a)
print(b)
c = [str(x) for x in range(10)]
print(c)
number = []
for i in b:
    # print(i)
    if i in c:
        number.append(i)
        # b.remove(i)
# print(number)
# print(b)
for i in b:
    if not i in c:
        print(i, end='')
print(*number, sep='')

['1', '5', '7', 'A', 'B', 'C', 'K', 'K']
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
ABCKK157


In [1]:
# 324
data = 'K1KA5CB7'
result = []
value = 0

for x in data:
    if x.isalpha():
        result.append(x)
    else:
        value += int(x)

result.sort()

if value != 0:
    result.append(str(value))

print(''.join(result))

ABCKK13


In [3]:
# 325
# aabbaccc
# 2a2ba3c

def solutions(s):
    answer = len(s)

    for step in range(1, len(s) // 2 + 1):
        compressed = ""
        prev = s[0:step]
        count = 1
        for j in range(step, len(s), step):
            if prev == s[j:j + step]:
                count += 1
            else:
                compressed += str(count) + prev if count >= 2 else prev
                prev = s[j:j + step]
                count = 1
        compressed += str(count) + prev if count >= 2 else prev
        answer = min(answer, len(compressed))
    return answer


solutions('aabbaccc')



7

In [24]:
#aabbaccc 2a2ba3c
data = 'ababcdcdababcdcd'
result = len(data)

for step in range(1, len(data) // 2 + 1):
    prev = data[0:step]
    compressed = ''
    count = 1
    # print(step, prev)
    for x in range(step, len(data), step):
        # print(prev, compressed, count)
        if prev == data[x:x + step]:
            count += 1
        else:
            compressed += str(count) + prev if count >= 2 else prev
            prev = data[x:x + step]
            count = 1
    # print(step, prev, compressed, count)

    compressed += str(count) + prev if count >= 2 else prev
    result = min(result, len(compressed))
    print(compressed)

print(result)

ababcdcdababcdcd
2ab2cd2ab2cd
ababcdcdababcdcd
ababcdcdababcdcd
ababcdcdababcdcd
ababcdcdababcdcd
ababcdcdababcdcd
2ababcdcd
9


In [26]:
def solution(s):
    answer = len(s)

    for step in range(1, len(s) // 2 + 1):
        prev = s[0:step]
        compressed = ''
        count = 1
        for x in range(step, len(s), step):
            if prev == s[x:x + step]:
                count += 1
            else:
                compressed += str(count) + prev if count >= 2 else prev
                prev = s[x:x + step]
                count = 1

        compressed += str(count) + prev if count >= 2 else prev
        answer = min(answer, min(compressed))
    return answer


solutions('aabbccaccc')

9

In [1]:
# 327
def rotate_a_matrix_by_90_degree(a):
    n = len(a)
    m = len(a[0])
    result = [[0] * n for _ in range(m)]
    for i in range(n):
        for j in range(m):
            result[j][n - i - 1] = a[i][j]
            # print(result)
    return result


def check(new_lock):
    lock_length = len(new_lock) // 3
    for i in range(lock_length, lock_length * 2):
        for j in range(lock_length, lock_length * 2):
            if new_lock[i][j] != 1:
                return False
    return True


def solution(key, lock):
    n = len(lock)
    m = len(key)

    new_lock = [[0] * (n * 3) for _ in range(n * 3)]

    for i in range(n):
        for j in range(n):
            new_lock[i + n][j + n] = lock[i][j]
            print(new_lock)

    for rotation in range(4):
        key = rotate_a_matrix_by_90_degree(key)
        for x in range(n * 2):
            for y in range(n * 2):
                for i in range(m):
                    for j in range(m):
                        new_lock[x + i][y + j] += key[i][j]

                if check(new_lock):
                    return True

                for i in range(m):
                    for j in range(m):
                        new_lock[x + i][y + j] -= key[i][j]
    return False


solution([[0, 0, 0], [1, 0, 0], [0, 1, 1]], [[1, 1, 1], [1, 1, 0], [1, 0, 1]])

[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0]]
[[0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 1, 1, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 

True

In [4]:
def rotate_a_matrix_by_90_degree(a):
    n = len(a)
    m = len(a[0])
    result = [[0] * n for _ in range(m)]
    for i in range(n):
        for j in range(m):
            result[j][n - i - 1] = a[i][j]
    return result


rotate_a_matrix_by_90_degree([[1, 1, 1], [0, 1, 0], [1, 0, 1]])

[[0, 0, 1], [0, 0, 0], [0, 0, 0]]

[[0, 0, 1], [0, 0, 1], [0, 0, 0]]

[[0, 0, 1], [0, 0, 1], [0, 0, 1]]

[[0, 0, 1], [0, 0, 1], [0, 0, 1]]

[[0, 0, 1], [0, 1, 1], [0, 0, 1]]

[[0, 0, 1], [0, 1, 1], [0, 0, 1]]

[[1, 0, 1], [0, 1, 1], [0, 0, 1]]

[[1, 0, 1], [0, 1, 1], [0, 0, 1]]

[[1, 0, 1], [0, 1, 1], [1, 0, 1]]



[[1, 0, 1], [0, 1, 1], [1, 0, 1]]

In [15]:
# 329 526
n = 6
k = 3
data = [[0] * (n + 1) for _ in range(n + 1)]
info = []

for x in [[3, 4], [2, 5], [5, 3]]:
    a, b = x
    data[a][b] = 1

l = 3
for y in [[3, 'D'], [15, 'L'], [17, 'D']]:
    x, c = y
    info.append((int(x), c))

dx = [0, 1, 0, -1]
dy = [1, 0, -1, 0]


def turn(direction, c):
    if c == "L":
        direction = (direction - 1) % 4
    else:
        direction = (direction + 1) % 4
    return direction


def simulate():
    x, y = 1, 1
    data[x][y] = 2
    direction = 0
    time = 0
    index = 0
    q = [(x, y)]
    while True:
        nx = x + dx[direction]
        ny = y + dy[direction]
        if 1 <= nx <= n and 1 <= ny <= n and data[nx][ny] != 2:
            if data[nx][ny] == 0:
                data[nx][ny] = 2
                q.append((nx, ny))
                print(q)
                px, py = q.pop(0)
                data[px][py] = 0
            if data[nx][ny] == 1:
                data[nx][ny] = 2
                q.append((nx, ny))
        else:
            time += 1
            break
        x, y = nx, ny
        time += 1
        if index < l and time == info[index][0]:
            direction = turn(direction, info[index][1])
            index += 1
    return time


print(simulate())




[(1, 1), (1, 2)]
[(1, 2), (1, 3)]
[(1, 3), (1, 4)]
[(1, 4), (2, 4)]
[(2, 4), (3, 4), (4, 4)]
[(3, 4), (4, 4), (5, 4)]
[(4, 4), (5, 4), (6, 4)]
9


In [30]:
import numpy as np

n = 6
k = 3
apple = []
trans = []
map = [[0] * n for _ in range(n + 1)]
for x in [[3, 4], [2, 5], [5, 3]]:
    apple.append(x)
    map[x[0]][x[1]] = 1

for x in [[3, 'D'], [15, 'L'], [17, 'D']]:
    trans.append(x)

# 동 남 북 서
dx = [0, 1, 0, -1]
dy = [1, 0, -1, 0]
direction = 0
x, y = 1, 1
times = 0
index = 0
q = [(x, y)]
print(apple)
print(trans)
print(map)
while True:
    print(np.array(map))
    nx = x + dx[direction]
    ny = y + dy[direction]
    if 1 <= nx <= n and 1 <= ny <= n and map[nx][ny] != 2:
        if map[nx][ny] == 0:
            map[nx][ny] = 2
            q.append((nx, ny))
            px, py = q.pop(0)
            map[px][py] = 0
        elif map[nx][ny] == 1:
            map[nx][ny] = 2
            q.append((nx, ny))
    else:
        times += 1
        break
    x, y = nx, ny
    times += 1
    if index < l and times == info[index][0]:
        direction = turn(direction, info[index][1])
        index += 1
print(map)
print(times)


[[3, 4], [2, 5], [5, 3]]
[[3, 'D'], [15, 'L'], [17, 'D']]
[[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 2 1]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 2 1]
 [0 0 0 0 2 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 2 0]
 [0 0 0 0 2 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]

In [1]:
#A12 333 / 527

In [ ]:
def possible(answer):
    for x, y, stuff in answer:
        if stuff == 0:
            #기둥은 바닥 or 보의 한쪽 끝부분  위 or 다른 기둥
            if y == 0 or [x - 1, y, 1] in answer or [x, y, 1] in answer
                or [x, y - 1, 0] in answer:
            continue
            return False
        elif stuff == 1:
            # 보는 한쪽 끝부분이 기둥 위에 or 양쪽 끝부분이 다른 보와 동시에 연결
            if [x, y - 1, 0] in answer or [x + 1, y - 1, 0] in answer
                or ([x - 1, y, 1] in answer and [x + 1, y, 1] in answer):
            continue
            return False
    return True


def solution(n, build_frame):
    answer = []
    for frame in build_frame:
        x, y, stuff, operate = frame
        if operate == 0:
            answer.remove([x, y, stuff])
            if not possible(answer):
                answer.append([x, y, stuff])
        if operate == 1:
            answer.append([x, y, stuff])
            if not possible(answer):
                answer.remove([x, y, stuff])
    return sorted(answer)

